name: Cypress Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run regression tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'qa'
        type: choice
        options:
          - local
          - dev
          - qa
          - staging
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'smoke'
        type: choice
        options:
          - all
          - smoke
          - regression
          - api
          - e2e

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Smoke Tests
        run: npm run test:smoke
        env:
          QA_USERNAME: ${{ secrets.QA_USERNAME }}
          QA_PASSWORD: ${{ secrets.QA_PASSWORD }}
          CYPRESS_ENVIRONMENT: qa

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-smoke
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-smoke
          path: cypress/videos
          retention-days: 7

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-smoke
          path: cypress/reports
          retention-days: 30

  regression-tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 2 * * *' || github.event_name == 'workflow_dispatch'
    
    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Regression Tests
        run: npm run test:regression -- --browser ${{ matrix.browser }}
        env:
          QA_USERNAME: ${{ secrets.QA_USERNAME }}
          QA_PASSWORD: ${{ secrets.QA_PASSWORD }}
          CYPRESS_ENVIRONMENT: qa

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-regression-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-regression-${{ matrix.browser }}
          path: cypress/videos
          retention-days: 7

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-regression-${{ matrix.browser }}
          path: cypress/reports
          retention-days: 30

  manual-tests:
    name: Manual Test Execution
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "all" ]; then
            npm run test:${{ github.event.inputs.environment }}
          else
            npm run test:${{ github.event.inputs.test_type }}
          fi
        env:
          QA_USERNAME: ${{ secrets.QA_USERNAME }}
          QA_PASSWORD: ${{ secrets.QA_PASSWORD }}
          CYPRESS_ENVIRONMENT: ${{ github.event.inputs.environment }}

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts-manual
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports
          retention-days: 30

